Int-one/DDogDog

BackEnd/DDogDog/src/main/java/com/ddogdog/controller/WalkLogController.java
BackEnd/DDogDog/src/main/java/com/ddogdog/model/dao/WalkLogDao.java
BackEnd/DDogDog/src/main/java/com/ddogdog/model/dto/Pet.java
BackEnd/DDogDog/src/main/java/com/ddogdog/model/dto/Together.java
BackEnd/DDogDog/src/main/java/com/ddogdog/model/dto/Trade.java
BackEnd/DDogDog/src/main/java/com/ddogdog/service/WalkLogService.java
BackEnd/DDogDog/src/main/java/com/ddogdog/service/WalkLogServiceImpl.java
BackEnd/DDogDog/src/main/resources/mappers/WalkLogMapper.xml
BackEnd/final.sql

**
**
1. ERD 변경사항에 맞춰 데이터 테이블의 컬럼명을 변경하고, 기존 timestamp형태로 저장하던 날짜정보를 datetime으로 변경하여 1970년 1월 1일 00시 00분 이전의 데이터도 저장할 수 있도록 업데이트.
2. 변경한 데이터 테이블에 맞춰 더미 데이터를 새로 생성하여 저장, user_id를 email형식으로 지정.
3. user_id를 이용해 해당 유저의 가장 최근 산책 데이터를 반환하는 API를 생성
4. 전체 유저의 가장 최근 산책 데이터 10개를 반환하는 API 생성
**
user_id를 get방식으로 url path에 추가하여 요청받는데 post로 변경하는게 좋을까요?
**
1. 유저의 가장 최근 산책 데이터를 반환하는 API 주소 : http://localhost:8081/api/walklog/latest/:user_id
2. 전체 유저의 가장 최근 산책 데이터 10개를 반환하는 API 주소 : http://localhost:8081/api/walklog
X

[Feat] ERD 변경사항 반영 및 API 추가

---

BackEnd/DDogDog/src/main/resources/mappers/PetMapper.xml
BackEnd/DDogDog/src/main/resources/mappers/TradeMapper.xml

**
**
DB 수정으로 인해 맞지 않았던 Mapper 수정
**
**
|기능|스크린샷|
|:--:|:--:|
|||

[Fix] Mapper수정

---

.gitignore
BackEnd/DDogDog/src/main/java/com/ddogdog/controller/DogWalkerController.java
BackEnd/DDogDog/src/main/java/com/ddogdog/controller/UserController.java
BackEnd/DDogDog/src/main/java/com/ddogdog/model/dto/DogWalker.java
BackEnd/DDogDog/src/main/resources/mappers/DogWalkerMapper.xml
BackEnd/final.sql
FrontEnd/ddogdog2/index.html
FrontEnd/ddogdog2/src/router/index.js
FrontEnd/ddogdog2/src/views/walk/WalkLog.vue

Closes #15 
**
**
1. 유저가 도그워커 등록 시 도그워커로 변경
2. 유저가 도그워커 등록 시 도그워커 테이블에 해당 유저 데이터 초기화하여 생성
3. 도그워커에서 조회할 때 유저테이블과 조인하여 유저의 정보도 같이 조회
**
기능에 이상 없는지 확인 부탁드립니다!
**
X
X

[Fix] 도그워커 등록, 도그워커 정보 조회 수정

---

BackEnd/DDogDog/src/main/java/com/ddogdog/controller/WalkLogController.java
BackEnd/DDogDog/src/main/resources/application.properties
FrontEnd/ddogdog2/index.html
FrontEnd/ddogdog2/src/router/index.js
FrontEnd/ddogdog2/src/views/walk/DataTest.vue
FrontEnd/ddogdog2/src/views/walk/WalkLog.vue

**
Closes #17 
**
1. walklog데이터를 불러오는 api 동작을 확인
2. 불러온 데이터를 사용해 polyline(경로) 그려지는 지 구현
**
**
|기능|스크린샷|
|:--:|:--:|
|경로|![poly](https://github.com/user-attachments/assets/ecd5aafc-8997-494c-9a9c-2c1f2a26fbd3)|

[Test] walklog로 경로 그리기

---

BackEnd/final.sql
FrontEnd/ddogdog2/src/views/walk/DataTest.vue
FrontEnd/ddogdog2/src/views/walk/WalkLog.vue

**
**
walklog 테이블의 더미데이터 중 walk_path 데이터가 위치 및 시간을 저장한 배열과 duration이 있었는데 duration 제거
duration을 제거하며 walk_path의 path가 walk_path에 대응하도록 변경
변경된 더미데이터에 맞게 테스트 파일 수정
**
**
|기능|스크린샷|
|:--:|:--:|
|변경된 후 walklog|![walklog](https://github.com/user-attachments/assets/e54030c6-2591-49b4-acd2-49339e232ab6)|

[Fix] walklog의 walk_path 수정

---

BackEnd/DDogDog/src/main/resources/mappers/PetMapper.xml
FrontEnd/ddogdog2/src/router/index.js
FrontEnd/ddogdog2/src/views/main/MainView.vue

**
Closes #27 
**
메인 페이지의 반려견 정보에 carousel기능을 추가
각 반려견마다 최종 산책일자 데이터를 받아 계산하여 표시하도록 수정
산책가기 클릭 시 산책 기록 페이지로 이동 기능 추가
**
**
|기능|스크린샷|
|:--:|:--:|
|메인화면|![main](https://github.com/user-attachments/assets/6c735e8d-1850-45c8-acdc-c228b30f40a0)|

[Feat] 메인페이지 업데이트

---

FrontEnd/ddogdog2/src/views/main/MainView.vue

[Fix] 메인페이지 수정

---

BackEnd/DDogDog/src/main/java/com/ddogdog/controller/CandController.java
BackEnd/DDogDog/src/main/java/com/ddogdog/controller/DogWalkerController.java
BackEnd/DDogDog/src/main/java/com/ddogdog/controller/PetLogController.java
BackEnd/DDogDog/src/main/java/com/ddogdog/controller/PhotoController.java
BackEnd/DDogDog/src/main/java/com/ddogdog/controller/ResultController.java
BackEnd/DDogDog/src/main/java/com/ddogdog/controller/TogetherController.java
BackEnd/DDogDog/src/main/java/com/ddogdog/controller/TradeController.java

모든 Controller에 `@CrossOrigin("*")` 추가

[Fix] CrossOrigin

---

BackEnd/DDogDog/src/main/java/com/ddogdog/model/dto/DogWalker.java
BackEnd/DDogDog/src/main/resources/mappers/DogWalkerMapper.xml
FrontEnd/ddogdog2/src/views/dogwalker/DogWalkerDetailView.vue
FrontEnd/ddogdog2/src/views/dogwalker/DogWalkerListView.vue
FrontEnd/ddogdog2/src/views/dogwalker/DogWalkerProfileView.vue

도그워커 프로필 등록 프론트엔드 구현 
Closes #34 
- 도그워커 프로필 등록 폼 UI 제작
- 'PUT /dogwalker/profile` API 연동 완료
- 등록 성공 시 알림 메시지 및 실패 시 오류 메시지 표시
- MyBatis 매퍼 파일 수정 (`DogWalkerMapper.xml`) 및 조건부 업데이트 처리
- 데이터베이스 테이블 구조 수정 (`time`, `all` 컬럼 추가 및 백틱 적용)
-  API 연동 시 백엔드 응답 데이터를 처리하는 로직 검토가 필요
- `DogWalkerMapper.xml`의 조건부 업데이트 쿼리 로직 검토
X
|기능|스크린샷|
|:--:|:--:|

도그워커프로필등록및수정

---

BackEnd/DDogDog/src/main/java/com/ddogdog/controller/UserController.java
BackEnd/final.sql
FrontEnd/ddogdog2/src/router/index.js
FrontEnd/ddogdog2/src/stores/auth.js
FrontEnd/ddogdog2/src/views/auth/LocationInputView.vue
FrontEnd/ddogdog2/src/views/dogwalker/DogWalkerListView.vue

Closes #36 
- 로그인 시 사용자 지역 정보를 로컬스토리지에 저장 
- 회원가입 시 위치 정보 인증 로직 구현
---
- **백엔드 수정**:
- 로그인 성공 시 사용자 지역 정보를 반환하도록 API 수정.
- `UserController`에서 지역 정보를 JWT와 함께 응답에 포함.
- **프론트엔드 구현**:
- 로그인 성공 시 사용자 지역 정보를 로컬스토리지에 저장.
- `auth.js`에서 사용자 지역 정보를 처리하고 저장하는 로직 추가.
- 이후 로컬스토리지의 지역 정보를 활용할 수 있도록 설정.
- **Kakao 지도 API 사용**:
- `LocationInputView.vue`에서 사용자의 현재 위치를 가져와 Kakao 지도 API로 주소 변환.
- 변환된 주소를 '읍/면/동'까지만 추출하여 표시.
- **위치 확인 UI**:
- 위치 정보 확인 화면에서 "맞아요" 버튼 클릭 시, 변환된 주소를 Pinia 스토어에 저장.
- "아니에요" 버튼 클릭 시 위치 정보를 다시 조회하여 업데이트.
- **Pinia와의 연동**:
- 위치 정보 저장 로직을 `signupStore`와 연동.
- 다음 단계(정보 확인 페이지)로 주소 데이터를 전달.
- 위치 정보 가져오기 실패 시 오류 처리 및 사용자에게 알림 추가.
- Kakao 지도 API 로드 문제 시 사용자에게 명확한 메시지 제공.
---
**프론트엔드 로컬스토리지 저장 구조**:
- `localStorage` 키/값 관리 방식 검토.
**주소 변환 로직 검토**:
- Kakao 지도 API로 변환된 주소에서 '읍/면/동'만 추출하는 …

[Feat] 사용자 위치정보 확인 및 인증 로직 구현

---

FrontEnd/ddogdog2/src/router/index.js

index.js에서 conflict 수정하며 발생한 오류 수정

[!HotFix] conflict 수정

---

FrontEnd/ddogdog2/src/components/BottomNavBar.vue

*하단 메뉴바 컴포넌트에서 발생한 UI 오류 수정*
Closes #44 
- 메뉴 아이콘과 메뉴명 텍스트 간격을 조정하여 UI를 개선
- 메뉴 선택 시 배경색이 변경되지 않도록 CSS 오류를 수정
- CSS 수정 추가 피드백 
- 모바일 환경에서의 UI 최적화를 목표
- 선택된 메뉴의 `:focus` 및 `:active` 상태에서 배경색이 투명하도록 처리
|기능|스크린샷|
|:--:|:--:|

[Fix]하단메뉴바 컴포넌트오류수정

---

FrontEnd/ddogdog2/src/components/PetIcon.vue
FrontEnd/ddogdog2/src/views/main/MainView.vue

**
Closes #46 
**
메인화면에 산책 데이터 요약 표시 및 산책가기 버튼 제거
**
**
|기능|스크린샷|
|:--:|:--:|
|메인화면|![main](https://github.com/user-attachments/assets/5006ca39-116a-4a49-bb80-325f4e8ce86e)|

[Feat]메인화면 수정

---

BackEnd/DDogDog/src/main/resources/mappers/WalkLogMapper.xml
FrontEnd/ddogdog2/src/components/PetIcon.vue
FrontEnd/ddogdog2/src/router/index.js
FrontEnd/ddogdog2/src/stores/pet.js
FrontEnd/ddogdog2/src/stores/walk.js
FrontEnd/ddogdog2/src/views/main/MainView.vue
FrontEnd/ddogdog2/src/views/walk/WalkMainView.vue
FrontEnd/ddogdog2/src/views/walk/WalkView.vue
FrontEnd/ddogdog2/src/views/walk/Walking.vue
FrontEnd/ddogdog2/src/views/walk/WalkingView.vue

**
Closes #50 
**
1. 메인 화면을 구상한 대로 구성
2. 보여주는 나의 반려견 정보를 pinia의 goWith에 상태를 저장하도록 설정
3. 산책 가기 버튼을 누르면 Walking페이지로 이동하도록 라우터 설정
**
**
|기능|스크린샷|
|:--:|:--:|
|산책 메인 화면|![walk](https://github.com/user-attachments/assets/126841bd-e1e6-4636-9c2d-dfcccf96bf2c)|

[Feat] 산책 탭 메인화면 구현

---

BackEnd/DDogDog/src/main/java/com/ddogdog/model/dto/Trade.java
BackEnd/DDogDog/src/main/resources/mappers/TradeMapper.xml
BackEnd/final.sql

Trade 기능 구현을 위해 필요한 컬럼들 추가, 백엔드 dto, Mapper 수정

[Feat] Trade 수정

---

BackEnd/DDogDog/src/main/java/com/ddogdog/controller/TradeController.java
BackEnd/DDogDog/src/main/java/com/ddogdog/model/dao/TradeDao.java
BackEnd/DDogDog/src/main/java/com/ddogdog/service/TradeService.java
BackEnd/DDogDog/src/main/java/com/ddogdog/service/TradeServiceImpl.java
BackEnd/DDogDog/src/main/resources/application.properties
BackEnd/DDogDog/src/main/resources/mappers/TradeMapper.xml

**
Closes #55 
**
Trade 생성 API 구현
해드려요의 경우 superId가 반드시 필요(테이블에 존재해야함)
해주세요의 경우 userId가 반드시 필요(테이블에 존재해야함)
**
test data
```
{
"kind": "해주세요",
"tradeStartTime": "2024-11-15T10:00:00",
"tradeEndTime": "2024-11-15T11:00:00",
"cost": 12345,
"region": "test",
"detail": "test",
"state": null,
"largeDog": 1,
"superId": "test@test.com",
"userId": null,
"pets": [1, 2, 3]
}
```
**
|기능|스크린샷|
|:--:|:--:|
|||

[Feat] Trade 생성 API

---

BackEnd/DDogDog/src/main/resources/application.properties

[Fix] db id & pw

---

.gitignore

application.properties를 무시하도록 설정

[Fix] gitignore에 application.properties추가

---

FrontEnd/ddogdog2/src/components/PetIcon.vue
FrontEnd/ddogdog2/src/stores/pet.js
FrontEnd/ddogdog2/src/views/walk/WalkMainView.vue
FrontEnd/ddogdog2/src/views/walk/WalkingView.vue

**
Closes #63 
**
1. 산책 가는 반려견들만 저장하여 PetIcon컴포넌트로 표시
2. 해당 반려견들을의 이미지를 선택하여 현재 관리중인 반려견 표시 - >실제 관리하는 기능은 추가해야함
3. 현재까지 산책한 거리와 시간을 계산하여 실시간으로 표시
4. 산책 종료하면 산책 기록 추가 api호출, 저장 - petlog데이터 생성하고 보내야함 -> pet store에 petlog를 생성하여 관리 예정
**
추가로 구현해야 하는 기능 확인 및 추가 기능 피드백 요망
**
|기능|스크린샷|
|:--:|:--:|
|산책중 페이지|<img width="182" alt="스크린샷 2024-11-24 오전 12 26 56" src="https://github.com/user-attachments/assets/bf75a2f5-4885-4a72-89e7-5b1bc2bef345">|

[Feat] 산책중 페이지 구현

---

BackEnd/DDogDog/src/main/java/com/ddogdog/controller/TradeController.java
BackEnd/DDogDog/src/main/java/com/ddogdog/model/dao/TradeDao.java
BackEnd/DDogDog/src/main/java/com/ddogdog/service/TradeService.java
BackEnd/DDogDog/src/main/java/com/ddogdog/service/TradeServiceImpl.java
BackEnd/DDogDog/src/main/resources/mappers/TradeMapper.xml
FrontEnd/ddogdog2/src/components/WalkLog.vue

**
Closes #65 
**
1. 해주세요 거래 목록 - "http://localhost:8081/api/trade/please"
2. 해드려요 거래 목록 - "http://localhost:8081/api/trade/will"
3. 해주세요에 있는 반려견 정보 - "http://localhost:8081/api/trade/pets/{tradeId}"
4. 내가 지원한 해주세요 목록 - "http://localhost:8081/api/trade/cand/{candId}"
**
**
|기능|스크린샷|
|:--:|:--:|
|해주세요|<img width="641" alt="스크린샷 2024-11-24 오후 3 22 32" src="https://github.com/user-attachments/assets/700536b4-b66f-4ea6-991d-d2acc1bc687d">|
|해드려요|<img width="622" alt="스크린샷 2024-11-24 오후 3 23 45" src="https://github.com/user-attachments/assets/82e352f3-377e-4b06-b56e-07f354d25921">|
|반려견 정보|<img width="622" alt="스크린샷 2024-11-24 오후 3 25 19" src="https://github.com/user-attachments/assets/8bce61be-248c-4d05-9562-628212290616">|
|지원 목록|<img width="625" alt="스크린샷 2024-11-24 오후 3 26 02" …

[Feat]Trade페이지 구현에 필요한 API

---

BackEnd/DDogDog/src/main/java/com/ddogdog/service/TradeServiceImpl.java

**
**
해주세요 목록 요청API 사용 시 반환 데이터들의 Key가 snace_case인 것을 camelCase로 변경
**
**
|기능|스크린샷|
|:--:|:--:|
|해주세요|<img width="623" alt="스크린샷 2024-11-24 오후 4 33 17" src="https://github.com/user-attachments/assets/d348bb1f-26bf-46cd-a80b-10ac24ce7a13">|

[Fix]해주세요 거래 목록 요청시 카멜케이스로

---

BackEnd/DDogDog/src/main/resources/mappers/TradeMapper.xml

해주세요 목록을 가져올 때 작성자의 닉네임도 가져오도록 수정

[Fix] add nickname

---

BackEnd/DDogDog/src/main/resources/mappers/TradeMapper.xml

api/trade/please에 super_id, user_id도 반환하도록 수정

[Fix] add super, userid

---

FrontEnd/ddogdog2/src/views/auth/LoginPageView.vue

* 로그인 오류 관련 Closes #78 
* 로그인 데이터 키(`email`, `password`)와 서버 API의 요청 데이터 일치
* CORS 오류 발생 원인 분석 및 요청 방식 점검
* 에러 메시지 UI 개선 (사용자가 쉽게 이해할 수 있도록 표시)
* `useAuthStore`와의 데이터 연동 확인 및 개선
* 성공적인 로그인 시 페이지 이동 로직 정상화
* `email`과 `password`의 키 이름 수정으로 기존 API와의 일치성을 확인 요망
* 로그인 성공 후 페이지 이동 로직(`/`로 이동)이 정상 작동하는지 검토 요망
* CORS 오류는 클라이언트와 서버 간 데이터 구조 불일치로 인해 발생
*  데이터를 서버와 동일하게 조정하여 해결
* 스토어를 활용한 로그인 로직과 데이터 관리의 일관성을 유지
|기능|스크린샷|
|:--:|:--:|

[Fix]로그인 CORS 오류 해결

---

BackEnd/DDogDog/src/main/java/com/ddogdog/config/WebConfig.java
BackEnd/DDogDog/src/main/java/com/ddogdog/controller/PetLogController.java
FrontEnd/ddogdog2/src/stores/petLog.js
FrontEnd/ddogdog2/src/views/walk/WalkMainView.vue
FrontEnd/ddogdog2/src/views/walk/WalkingView.vue

1. 반려견 사진 즉시 반영
2. petlog스토어 수정

[Feat] 반려견 사진 즉시 반영, petlog스토어 수정

---

BackEnd/DDogDog/src/main/java/com/ddogdog/controller/PetController.java
BackEnd/DDogDog/src/main/java/com/ddogdog/model/dao/PetDao.java
BackEnd/DDogDog/src/main/java/com/ddogdog/service/PetService.java
BackEnd/DDogDog/src/main/java/com/ddogdog/service/PetServiceImpl.java
BackEnd/DDogDog/src/main/resources/mappers/PetMapper.xml
FrontEnd/ddogdog2/src/views/walk/WalkMainView.vue

**
Closes #83 
**
1. 산책을 클릭하면 해당 산책 정보 표시
2. 해당 산책을 같이 간 반려견들 정보 표시
**
**
|기능|스크린샷|
|:--:|:--:|
|||

[Feat] 산책 상세보기

---

FrontEnd/ddogdog2/src/views/dogwalker/DoForMeDetailView.vue

- 거래 상세 페이지의 거래 데이터를 Pinia Store를 활용해 로드하도록 수정 
Closes #90 
- Pinia Store (`doforme.js`)에 `fetchTrades` 메서드 추가
- 거래 데이터를 Store에서 불러오는 방식으로 로직 변경
- 반려견 데이터 로드 방식은 기존 API 요청 방식을 유지
- 코드 일관성 유지 및 리팩토링
- Pinia Store 활용 부분의 구조 적합성 검토 요망
- 기존 방식과 새로운 방식의 통합 과정에서의 불필요한 로직은 없는지 확인 요망
- 반려견 데이터 로드는 별도 API 요청을 사용해 기존 방식 유지
- Pinia Store 사용으로 데이터 관리를 단순화
| 기능        | 스크린샷                                                                                   |
|:-----------:|:-----------------------------------------------------------------------------------------:|

[Fix]해주세요 거래 데이터 로직 개선

---

FrontEnd/ddogdog2/src/views/dogwalker/DogwalkerView.vue

[Fix] 해주세요 목록페이지 데이터 로드 오류 수정

---

FrontEnd/ddogdog2/src/components/DoForMeTab.vue
FrontEnd/ddogdog2/src/components/board/BoardList.vue
FrontEnd/ddogdog2/src/components/board/BoardSearchInput.vue
FrontEnd/ddogdog2/src/views/dogwalker/DogwalkerView.vue
FrontEnd/ddogdog2/src/views/main/MainView.vue
FrontEnd/ddogdog2/src/views/walk/WalkMainView.vue
FrontEnd/ddogdog2/src/views/walk/WalkingView.vue

[Fix] CSS 수정

---

.idea/.gitignore
.idea/DDogDog.iml
.idea/misc.xml
.idea/modules.xml
.idea/vcs.xml
BackEnd/.idea/.gitignore
BackEnd/.idea/BackEnd.iml
BackEnd/.idea/misc.xml
BackEnd/.idea/modules.xml
BackEnd/.idea/vcs.xml
BackEnd/DDogDog/src/main/resources/mappers/boardMapper.xml
FrontEnd/ddogdog2/src/components/PetIcon.vue
FrontEnd/ddogdog2/src/router/index.js
FrontEnd/ddogdog2/src/views/auth/EmailInputView.vue
FrontEnd/ddogdog2/src/views/auth/LocationInputView.vue

[FIx] css, 시연용 더미데이터 수정

---

FrontEnd/ddogdog2/src/router/index.js
FrontEnd/ddogdog2/src/views/auth/BirthGenderInputView.vue
FrontEnd/ddogdog2/src/views/auth/ConfirmationPageView.vue
FrontEnd/ddogdog2/src/views/auth/EmailInputView.vue
FrontEnd/ddogdog2/src/views/auth/HeightWeightInputView.vue
FrontEnd/ddogdog2/src/views/auth/LocationInputView.vue
FrontEnd/ddogdog2/src/views/auth/NicknameInputView.vue
FrontEnd/ddogdog2/src/views/auth/PasswordInputView.vue
FrontEnd/ddogdog2/src/views/auth/PhoneNumberInputView.vue
FrontEnd/ddogdog2/src/views/auth/SignupPageView.vue

* 회원가입 단계별 UI 작업 (#이슈번호)
* 회원가입 단계별 페이지 UI를 통일된 디자인으로 구현
* 각 단계별 작업 내용:
- **이메일 입력 페이지**: 입력 필드와 버튼 스타일 개선
- **비밀번호, 닉네임, 전화번호 입력 페이지**: 통일된 디자인 적용
- **생년월일 및 성별 입력 페이지**: 버튼으로 성별 선택, 입력 값 유효성 검사
- **신장 및 체중 입력 페이지**: 정사각형 입력 필드 및 마우스 휠로 값 조정 기능 추가
- **위치 정보 확인 페이지**: Kakao 지도 API로 지도 표시 및 위치 확인 기능 추가
- **회원 정보 확인 페이지**: 테이블 형태로 정보를 보기 쉽게 정리, 둥근 사각형 컨테이너로 디자인 개선
* Kakao 지도 API 활용 부분에서 개선할 사항이나 로딩 최적화 필요 여부
* 코드 스타일 및 구조에 대한 추가 피드백
* 각 페이지별 유효성 검사 및 데이터 처리가 완벽히 동작하도록 추가 테스트 필요
| 기능 | 스크린샷|
|:--:|:--:|
| 회원가입 약관동의 페이지 | ![스크린샷 2024-12-16 224447](https://github.com/user-attachments/assets/a856031d-dd0a-40de-9886-405b6015909a) |
| 이메일 입력 페이지 | ![스크린샷 2024-12-17 001350](https://github.com/user-attachments/assets/de4dd6be-09c4-4c3f-935c-e5663f47f09b) |
| 비밀번호 입력 페이지 |  ![스크린샷 2024-12-17 …

[Feat]회원가입단계별페이지UI구현
